### Лабораторная работа № 4

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, max_error
from sklearn.metrics import confusion_matrix, classification_report
from imblearn.under_sampling import RandomUnderSampler
from sklearn.preprocessing import StandardScaler
import tensorflow as tf
import numpy as np
import pandas as pd

### Загрузка данных и разделение на выборки

In [ ]:
# Регрессия
df = pd.read_csv("diamonds.csv", index_col=0)
df = pd.get_dummies(df, columns=['cut','color','clarity'])
display(df)

y = df["price"]
X = df.drop(["price"], axis=1)

X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(X, y, test_size=0.2)

# Классификация

data = pd.read_csv("airlines_task.csv", index_col=0).drop_duplicates()

data.loc[:, ["Airline", "AirportFrom", "AirportTo", "Flight"]].nunique(axis=0)
data.dropna(inplace=True)
data_encoded = pd.get_dummies(data, columns=["Airline"], dtype=int).reset_index(drop=True)
routes = pd.Series(data=(data_encoded.AirportTo + data_encoded.AirportFrom), name="Route")
routes
data_encoded: pd.DataFrame = pd.concat([data_encoded, routes], axis=1).drop(["AirportTo", "AirportFrom"], axis=1)
data_encoded.rename({0: "Route"}, axis=1, inplace=True)
data_encoded.Route.value_counts()
label_map = dict(zip(data_encoded.Route.unique().tolist(), np.arange(0, data_encoded.Route.unique().shape[0])))
label_map
data_encoded.Route
data_encoded.Route = data_encoded.Route.map(lambda x: label_map.get(x))
data_encoded.Route

df = data_encoded
display(df)

y = df['Delay']
X = df.drop(['Delay'], axis=1)

underSampler = RandomUnderSampler(sampling_strategy='majority')
X_under_sample, y_under_sample = underSampler.fit_resample(X, y)

X_train_clf, X_test_clf, y_train_clf, y_test_clf = train_test_split(X_under_sample, y_under_sample, test_size=0.2, random_state = 4)

scaler = StandardScaler()

scaler.fit(X_train_clf, y_train_clf)
X_train_std_clf = scaler.transform(X_train_clf)
X_test_std_clf = scaler.transform(X_test_clf)

,carat,depth,table,price,x,y,z,cut_Fair,cut_Good,cut_Ideal,...,color_I,color_J,clarity_I1,clarity_IF,clarity_SI1,clarity_SI2,clarity_VS1,clarity_VS2,clarity_VVS1,clarity_VVS2
1,0.23,61.5,55.0,326,3.95,3.98,2.43,0,0,1,...,0,0,0,0,0,1,0,0,0,0
2,0.21,59.8,61.0,326,3.89,3.84,2.31,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,0.23,56.9,65.0,327,4.05,4.07,2.31,0,1,0,...,0,0,0,0,0,0,1,0,0,0
4,0.29,62.4,58.0,334,4.20,4.23,2.63,0,0,0,...,1,0,0,0,0,0,0,1,0,0
5,0.31,63.3,58.0,335,4.34,4.35,2.75,0,1,0,...,0,1,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53936,0.72,60.8,57.0,2757,5.75,5.76,3.50,0,0,1,...,0,0,0,0,1,0,0,0,0,0
53937,0.72,63.1,55.0,2757,5.69,5.75,3.61,0,1,0,...,0,0,0,0,1,0,0,0,0,0
53938,0.70,62.8,60.0,2757,5.66,5.68,3.56,0,0,0,...,0,0,0,0,1,0,0,0,0,0
53939,0.86,61.0,58.0,2757,6.15,6.12,3.74,0,0,0,...,0,0,0,0,0,1,0,0,0,0
53940,0.75,62.2,55.0,2757,5.83,5.87,3.64,0,0,1,...,0,0,0,0,0,1,0,0,0,0

,Flight,DayOfWeek,Time,Length,Delay,Airline_9E,Airline_AA,Airline_AS,Airline_B6,Airline_CO,...,Airline_HA,Airline_MQ,Airline_OH,Airline_OO,Airline_UA,Airline_US,Airline_WN,Airline_XE,Airline_YV,Route
0,3036,4.0,1195,131.0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,315,7.0,707,145.0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
2,6673,5.0,499,42.0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,2
3,3668,2.0,810,70.0,1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,3
4,623,5.0,985,143.0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254042,2699,7.0,910,62.0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1806
254043,3995,2.0,985,80.0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,769
254044,6474,6.0,652,138.0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,2341
254045,486,7.0,365,107.0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1843
254046,1037,4.0,605,150.0,1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1111

## Регрессия

### Без гиперпараметров

In [ ]:
model_regression = tf.keras.Sequential(
    [
        tf.keras.layers.Input(shape=(26,)),
        tf.keras.layers.Dense(256, activation="relu"),
        tf.keras.layers.Dense(512, activation="relu"),
        tf.keras.layers.Dropout(0.3),
        tf.keras.layers.Dense(128, activation="relu"),
        tf.keras.layers.Dropout(0.05),
        tf.keras.layers.Dense(64, activation="relu"),
        tf.keras.layers.Dropout(0.01),
        tf.keras.layers.Dense(1, activation="linear")
    ]
)

In [ ]:
model_regression.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_10 (Dense)            (None, 256)               6912

 dense_11 (Dense)            (None, 512)               131584

 dropout_6 (Dropout)         (None, 512)               0

 dense_12 (Dense)            (None, 128)               65664

 dropout_7 (Dropout)         (None, 128)               0

 dense_13 (Dense)            (None, 64)                8256

 dropout_8 (Dropout)         (None, 64)                0

 dense_14 (Dense)            (None, 1)                 65

=================================================================
Total params: 212,481
Trainable params: 212,481
Non-trainable params: 0
_________________________________________________________________

In [ ]:
model_regression.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.005), loss="mae")

In [ ]:
model_regression.fit(X_train_reg, y_train_reg, epochs=15)

Epoch 1/15
1349/1349 [==============================] - 16s 10ms/step - loss: 764.6655
Epoch 2/15
1349/1349 [==============================] - 16s 12ms/step - loss: 551.3365
Epoch 3/15
1349/1349 [==============================] - 11s 8ms/step - loss: 532.2971
Epoch 4/15
1349/1349 [==============================] - 10s 7ms/step - loss: 514.8426
Epoch 5/15
1349/1349 [==============================] - 13s 10ms/step - loss: 496.3486
Epoch 6/15
1349/1349 [==============================] - 11s 8ms/step - loss: 492.8710
Epoch 7/15
1349/1349 [==============================] - 11s 8ms/step - loss: 483.8077
Epoch 8/15
1349/1349 [==============================] - 11s 8ms/step - loss: 485.4829
Epoch 9/15
1349/1349 [==============================] - 10s 8ms/step - loss: 473.2744
Epoch 10/15
1349/1349 [==============================] - 10s 7ms/step - loss: 473.6246
Epoch 11/15
1349/1349 [==============================] - 11s 8ms/step - loss: 465.1137
Epoch 12/15
1349/1349 [==============================] - 11s 8ms/step - loss: 467.2729
Epoch 13/15
1349/1349 [==============================] - 11s 8ms/step - loss: 469.1127
Epoch 14/15
1349/1349 [==============================] - 11s 8ms/step - loss: 450.5947
Epoch 15/15
1349/1349 [==============================] - 10s 7ms/step - loss: 452.9843

In [ ]:
y_pred_reg = model_regression.predict(X_test_reg)

338/338 [==============================] - 1s 2ms/step

In [ ]:
print(mean_absolute_error(y_test_reg, y_pred_reg))
print(mean_squared_error(y_test_reg, y_pred_reg))
print(r2_score(y_test_reg, y_pred_reg))
print(max_error(y_test_reg, y_pred_reg))

347.974048075607
980900.5506879403
0.9373803543521773
77754.5078125

### Классификация

In [ ]:
model_classification = tf.keras.Sequential(
    [
        tf.keras.layers.Input(shape=(23,)),
        tf.keras.layers.Dense(128, activation="relu"),
        tf.keras.layers.Dense(256, activation="relu"),
        tf.keras.layers.Dense(1024, activation="tanh"),
        tf.keras.layers.Dropout(0.1),
        tf.keras.layers.Dense(512, activation="tanh"),
        tf.keras.layers.Dropout(0.01),
        tf.keras.layers.Dense(128, activation="tanh"),
        tf.keras.layers.Dense(64, activation="tanh"),
        tf.keras.layers.Dense(32, activation="tanh"),
        tf.keras.layers.Dense(16, activation="tanh"),
        tf.keras.layers.Dense(1, activation="sigmoid")
    ]
)

In [ ]:
model_classification.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_24 (Dense)            (None, 128)               3072

 dense_25 (Dense)            (None, 256)               33024

 dense_26 (Dense)            (None, 1024)              263168

 dropout_11 (Dropout)        (None, 1024)              0

 dense_27 (Dense)            (None, 512)               524800

 dropout_12 (Dropout)        (None, 512)               0

 dense_28 (Dense)            (None, 128)               65664

 dense_29 (Dense)            (None, 64)                8256

 dense_30 (Dense)            (None, 32)                2080

 dense_31 (Dense)            (None, 16)                528

 dense_32 (Dense)            (None, 1)                 17

=================================================================
Total params: 900,609
Trainable params: 900,609
Non-trainable params: 0
_________________________________________________________________

In [ ]:
model_classification.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.00001), loss="binary_crossentropy")

In [ ]:
model_classification.fit(X_train_std_clf, y_train_clf, epochs=15)

Epoch 1/15
4322/4322 [==============================] - 92s 21ms/step - loss: 0.6578
Epoch 2/15
4322/4322 [==============================] - 89s 21ms/step - loss: 0.6517
Epoch 3/15
4322/4322 [==============================] - 91s 21ms/step - loss: 0.6495
Epoch 4/15
4322/4322 [==============================] - 89s 21ms/step - loss: 0.6473
Epoch 5/15
4322/4322 [==============================] - 90s 21ms/step - loss: 0.6458
Epoch 6/15
4322/4322 [==============================] - 89s 21ms/step - loss: 0.6445
Epoch 7/15
4322/4322 [==============================] - 92s 21ms/step - loss: 0.6434
Epoch 8/15
4322/4322 [==============================] - 91s 21ms/step - loss: 0.6430
Epoch 9/15
4322/4322 [==============================] - 89s 21ms/step - loss: 0.6422
Epoch 10/15
4322/4322 [==============================] - 91s 21ms/step - loss: 0.6416
Epoch 11/15
4322/4322 [==============================] - 90s 21ms/step - loss: 0.6411
Epoch 12/15
4322/4322 [==============================] - 90s 21ms/step - loss: 0.6408
Epoch 13/15
4322/4322 [==============================] - 92s 21ms/step - loss: 0.6402
Epoch 14/15
4322/4322 [==============================] - 90s 21ms/step - loss: 0.6398
Epoch 15/15
4322/4322 [==============================] - 91s 21ms/step - loss: 0.6398

In [ ]:
model_classification.predict(X_test_std_clf, verbose=None)[:5]

array([[0.45589998],
       [0.7947231 ],
       [0.32208836],
       [0.47245285],
       [0.5620817 ]], dtype=float32)

In [ ]:
y_pred = np.around(model_classification.predict(X_test_std_clf, verbose=None))
print(classification_report(y_test_clf, y_pred))
print(confusion_matrix(y_test_clf, y_pred))

              precision    recall  f1-score   support

           0       0.62      0.65      0.63     17239
           1       0.63      0.61      0.62     17332

    accuracy                           0.63     34571
   macro avg       0.63      0.63      0.63     34571
weighted avg       0.63      0.63      0.63     34571

[[11164  6075]
 [ 6805 10527]]

### Реализация персептрона

In [ ]:
class Activation:
    def callFunction(x):
        pass
    def callDerivative(x):
        pass

class Relu(Activation):
    @staticmethod
    def callFunction(x):
        return np.maximum(0,x)
    @staticmethod
    def callDerivative(x):
        return np.where(x > 0, 1.0, 0.0)

class Sigmoid(Activation):
    @staticmethod
    def callFunction(x):
        return 1 / (1 + np.exp(-x))
    @staticmethod
    def callDerivative(x):
        return Sigmoid.callFunction(x) * (1- Sigmoid.callFunction(x))
class TangH(Activation):

    @staticmethod
    def callFunction( x):
        return (np.exp(x) - np.exp(-x)) / (np.exp(x)+np.exp(-x))

    @staticmethod
    def callDerivative(x):
        return 1 - TangH.callFunction(x) ** 2

In [ ]:
class Layer:
    def __init__(self):
        self.input = None
        self.output = None

    def forward_propagation(self, input):
        raise NotImplementedError

    def backward_propagation(self, output_error):
        raise NotImplementedError

class FCLayer(Layer):

    def __init__(self, input_size, output_size):
        self.weights = np.random.rand(input_size, output_size) - 0.5
        self.bias = np.random.rand(1, output_size) - 0.5

    def forward_propagation(self, input_data):
        self.input = input_data
        self.output = np.dot(self.input, self.weights) + self.bias
        return self.output

    def backward_propagation(self, output_error, learning_rate):
        input_error = np.dot(output_error, self.weights.T)#dE/dx
        weights_error = np.dot(self.input.T, output_error)#dE/dw
        self.weights -= learning_rate * weights_error
        self.bias -= learning_rate * output_error
        return input_error #dE/dB так как равен de/dx

class ActivationLayer(Layer):
    def __init__(self, activation, activation_prime):
        self.activation = activation
        self.activation_prime = activation_prime

    def forward_propagation(self, input_data):
        self.input = input_data
        self.output = self.activation(self.input)
        return self.output

    def backward_propagation(self, output_error, learning_rate):
        return self.activation_prime(self.input) * output_error

In [ ]:
class LossFunction:
    def fun():
        pass
    def derivative():
        pass

class MeanSquaredError(LossFunction):
    def fun(y_true, y_pred):
        return np.mean(np.power(y_true-y_pred, 2))

    def derivative(y_true, y_pred):
        return 2*(y_pred-y_true)/y_true.size

In [ ]:
class NN:
    def __init__(self):
        self.layers = []
        self.loss = None
        self.loss_prime = None

    def add(self, layer):
        self.layers.append(layer)

    def compile(self, loss, loss_prime):
        self.loss = loss
        self.loss_prime = loss_prime

    def predict(self, input_data):
        samples = len(input_data)
        result = []

        for i in range(samples):
            output = input_data[i]
            for layer in self.layers:
                output = layer.forward_propagation(output)
            result.append(*output)

        return result

    def fit(self, x_train, y_train, epochs, learning_rate):

        samples = len(x_train)

        for i in range(epochs):

            for j in range(samples):
                output = x_train[j]
                for layer in self.layers:
                    output = layer.forward_propagation(output)

                error = self.loss_prime(y_train[j], output)
                for layer in reversed(self.layers):
                    error = layer.backward_propagation(error, learning_rate)